LOCAL_PATH := $(call my-dir)
TA_UUID := 1987f328-1755-9321-5441-43494343544c
TA_SUFFIX := .ta

$(warning PLATFORM_TDK_VERSION:$(PLATFORM_TDK_VERSION))
ifneq ($(filter $(PLATFORM_TDK_VERSION), 38 318),)
    ifeq ($(BOARD_AML_SOC_TYPE),)
        LOCAL_TA := v3/signed/$(TA_UUID)$(TA_SUFFIX)
    else
        LOCAL_TA := v3/dev/$(BOARD_AML_SOC_TYPE)/$(TA_UUID)$(TA_SUFFIX)
    endif
else
    LOCAL_TA := v2/signed/$(TA_UUID)$(TA_SUFFIX)
endif

$(warning CIPLUS_TA:$(LOCAL_TA))
ifeq ($(LOCAL_PATH)/$(LOCAL_TA), $(wildcard $(LOCAL_PATH)/$(LOCAL_TA)))
$(warning Install CIPLUS_TA:$(LOCAL_TA))

include $(CLEAR_VARS)
LOCAL_SRC_FILES := $(LOCAL_TA)
LOCAL_MODULE := $(TA_UUID)
LOCAL_LICENSE_KINDS := legacy_notice
LOCAL_LICENSE_CONDITIONS := notice
LOCAL_MODULE_SUFFIX := $(TA_SUFFIX)
LOCAL_STRIP_MODULE := false
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR)/lib/teetz
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := tee_ciplus_ta
LOCAL_LICENSE_KINDS := legacy_notice
LOCAL_LICENSE_CONDITIONS := notice
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_REQUIRED_MODULES := $(TA_UUID)
include $(BUILD_PHONY_PACKAGE)

endif
